cd david_anes
python3 main.py '2012'
python3 main.py '2016'
python3 main.py '2020'
cd ..


python3 pipeline_single.py data/anes2016/ds.pkl 'j1-large' 
python3 pipeline_single.py data/anes2016/ds.pkl 'EleutherAI/gpt-j-6B' 
python3 pipeline_single.py data/anes2016/ds.pkl 'j1-jumbo' 
python3 pipeline_single.py data/anes2016/ds.pkl 'EleutherAI/gpt-neo-2.7B' 
python3 pipeline_single.py data/anes2016/ds.pkl 'gpt2-xl' 
python3 pipeline_single.py data/anes2016/ds.pkl 'gpt3-davinci' 
python3 pipeline_single.py data/anes2016/ds.pkl 'gpt3-curie' 
python3 pipeline_single.py data/anes2016/ds.pkl 'gpt3-babbage' 
python3 pipeline_single.py data/anes2016/ds.pkl 'gpt3-ada' 
python3 pipeline_single.py data/anes2016/ds.pkl 'gpt2-large' 
python3 pipeline_single.py data/anes2016/ds.pkl 'gpt2-medium' 
python3 pipeline_single.py data/anes2016/ds.pkl 'gpt2' 
python3 pipeline_single.py data/anes2016/ds.pkl 'EleutherAI/gpt-neo-1.3B' 
python3 pipeline_single.py data/anes2016/ds.pkl 'EleutherAI/gpt-neo-125M' 

python3 pipeline_single.py data/anes2012/ds.pkl 'j1-large' 
python3 pipeline_single.py data/anes2012/ds.pkl 'EleutherAI/gpt-j-6B' 
python3 pipeline_single.py data/anes2012/ds.pkl 'j1-jumbo' 
python3 pipeline_single.py data/anes2012/ds.pkl 'EleutherAI/gpt-neo-2.7B' 
python3 pipeline_single.py data/anes2012/ds.pkl 'gpt2-xl' 
python3 pipeline_single.py data/anes2012/ds.pkl 'gpt3-davinci' 
python3 pipeline_single.py data/anes2012/ds.pkl 'gpt3-curie' 
python3 pipeline_single.py data/anes2012/ds.pkl 'gpt3-babbage' 
python3 pipeline_single.py data/anes2012/ds.pkl 'gpt3-ada' 
python3 pipeline_single.py data/anes2012/ds.pkl 'gpt2-large' 
python3 pipeline_single.py data/anes2012/ds.pkl 'gpt2-medium' 
python3 pipeline_single.py data/anes2012/ds.pkl 'gpt2' 
python3 pipeline_single.py data/anes2012/ds.pkl 'EleutherAI/gpt-neo-1.3B' 
python3 pipeline_single.py data/anes2012/ds.pkl 'EleutherAI/gpt-neo-125M' 

python3 pipeline_single.py data/anes2020/ds.pkl 'EleutherAI/gpt-j-6B' 
python3 pipeline_single.py data/anes2020/ds.pkl 'j1-large' 
python3 pipeline_single.py data/anes2020/ds.pkl 'j1-jumbo' 
python3 pipeline_single.py data/anes2020/ds.pkl 'EleutherAI/gpt-neo-2.7B' 
python3 pipeline_single.py data/anes2020/ds.pkl 'gpt2-xl' 
python3 pipeline_single.py data/anes2020/ds.pkl 'gpt3-davinci' 
python3 pipeline_single.py data/anes2020/ds.pkl 'gpt3-curie' 
python3 pipeline_single.py data/anes2020/ds.pkl 'gpt3-babbage' 
python3 pipeline_single.py data/anes2020/ds.pkl 'gpt3-ada' 
python3 pipeline_single.py data/anes2020/ds.pkl 'gpt2-large' 
python3 pipeline_single.py data/anes2020/ds.pkl 'gpt2-medium' 
python3 pipeline_single.py data/anes2020/ds.pkl 'gpt2' 
python3 pipeline_single.py data/anes2020/ds.pkl 'EleutherAI/gpt-neo-1.3B' 
python3 pipeline_single.py data/anes2020/ds.pkl 'EleutherAI/gpt-neo-125M' 

python3 pa_preprocessor.py
python3 pa_plot.py