# enumerate all categories for the congressional hearings dataset
# https://www.comparativeagendas.net/datasets_codebooks , under United States > Congressional Hearings
categories = {
    1: 'Macroeconomics',
    2: 'Civil Rights',
    3: 'Health',
    4: 'Agriculture',
    5: 'Labor',
    6: 'Education',
    7: 'Environment',
    8: 'Energy',
    9: 'Immigration',
    10: 'Transportation',
    12: 'Law and Crime',
    13: 'Social Welfare',
    14: 'Housing',
    15: 'Domestic Commerce',
    16: 'Defense',
    17: 'Technology',
    18: 'Foreign Trade',
    19: 'International Affairs',
    20: 'Government Operations',
    21: 'Public Lands',
    23: 'Culture',
}