# enumerate all the categories in the NY Times dataset
# url: https://www.comparativeagendas.net/datasets_codebooks, under United States > New York Times Headlines
categories = {
    1: 'Macroeconomics',
    2: 'Civil Rights, Minority Issues, and Civil Liberties',
    3: 'Health',
    4: 'Agriculture',
    5: 'Labor',
    6: 'Education',
    7: 'Environment',
    8: 'Energy',
    9: 'Immigration',
    10: 'Transportation',
    12: 'Law, Crime, and Family Issues',
    13: 'Social Welfare',
    14: 'Community Development and Housing Issues',
    15: 'Banking, Finance, and Domestic Commerce',
    16: 'Defense',
    17: 'Space, Science, Technology and Communications',
    18: 'Foreign Trade',
    19: 'International Affairs and Foreign Aid',
    20: 'Government Operations',
    21: 'Public Lands and Water Management',
    24: 'State and Local Government Administration',
    26: 'Weather and Natural Disasters',
    27: 'Fires',
    28: 'Arts and Entertainment',
    29: 'Sports and Recreation',
    30: 'Death Notices',
    31: 'Churches and Religion',
    99: 'Other, Miscellaneous, and Human Interest',
}